"""
Global Macro Intelligence Hub - Professional Report Manager
전문가급 PDF 리포팅 및 지능형 메일 전송 시스템
"""

from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
from datetime import datetime
from typing import Dict, Any, List, Tuple
import plotly.graph_objects as go
from dotenv import load_dotenv
import re

# .env 로드
load_dotenv()


class ProfessionalPDFReport(FPDF):
    """전문가급 한글 지원 PDF 리포트 클래스"""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.korean_font_name = None

    def find_korean_font(self) -> Tuple[bool, str]:
        """
        시스템에서 한글 폰트 자동 탐지

        Returns:
            (성공 여부, 폰트 경로)
        """
        # Windows 폰트 경로
        font_paths = [
            "C:/Windows/Fonts/NanumGothic.ttf",      # 나눔고딕
            "C:/Windows/Fonts/malgun.ttf",            # 맑은 고딕
            "C:/Windows/Fonts/NanumBarunGothic.ttf", # 나눔바른고딕
            "C:/Windows/Fonts/gulim.ttc",             # 굴림
        ]

        for path in font_paths:
            if os.path.exists(path):
                return True, path

        return False, None

    def setup_korean_font(self) -> bool:
        """한글 폰트 설정"""
        try:
            success, font_path = self.find_korean_font()

            if success:
                font_name = os.path.splitext(os.path.basename(font_path))[0]
                self.add_font(font_name, '', font_path, uni=True)
                self.korean_font_name = font_name
                print(f"[OK] Korean font set: {font_name}")
                return True
            else:
                print("[WARN] Korean font not found. Using English font.")
                return False
        except Exception as e:
            print(f"[WARN] Korean font setup failed: {e}")
            return False

    def header(self):
        """페이지 헤더"""
        # 그라디언트 효과 (색상 박스)
        self.set_fill_color(102, 126, 234)  # #667eea
        self.rect(0, 0, 210, 45, 'F')

        # 타이틀
        self.set_font('Arial', 'B', 26)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, '', 0, 1)
        self.cell(0, 10, 'GLOBAL MACRO INTELLIGENCE', 0, 1, 'C')

        # 서브타이틀
        self.set_font('Arial', 'I', 11)
        self.cell(0, 6, 'Professional Critical Analysis Report', 0, 1, 'C')

        self.ln(8)

    def footer(self):
        """페이지 푸터"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)

        # 왼쪽: 생성 정보
        self.cell(0, 10, f'Generated by Claude Sonnet 4 | Page {self.page_no()}', 0, 0, 'C')

    def section_header(self, number: str, title: str, color: Tuple[int, int, int] = (52, 73, 94)):
        """섹션 헤더"""
        self.ln(8)

        # 섹션 번호 박스
        self.set_fill_color(102, 126, 234)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 14)
        self.cell(15, 10, number, 0, 0, 'C', True)

        # 섹션 제목
        self.set_text_color(*color)
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, f'  {title}', 0, 1, 'L')

        # 구분선
        self.set_draw_color(102, 126, 234)
        self.set_line_width(0.7)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def add_key_value_box(self, items: List[Tuple[str, str]]):
        """키-값 박스 (회색 배경)"""
        self.set_fill_color(248, 249, 250)
        self.set_draw_color(220, 220, 220)

        y_start = self.get_y()

        for key, value in items:
            self.set_font('Arial', 'B', 10)
            self.set_text_color(52, 73, 94)
            self.cell(50, 7, f'{key}:', 0, 0)

            self.set_font('Arial', '', 10)
            self.set_text_color(0, 0, 0)
            self.multi_cell(0, 7, str(value))

        # 박스 그리기
        y_end = self.get_y()
        self.rect(10, y_start - 2, 190, y_end - y_start + 4)

        self.ln(3)

    def add_text_with_font(self, text: str, size: int = 10, bold: bool = False):
        """한글 지원 텍스트 추가"""
        if self.korean_font_name:
            style = 'B' if bold else ''
            self.set_font(self.korean_font_name, style, size)
        else:
            style = 'B' if bold else ''
            self.set_font('Arial', style, size)

        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, text)

    def add_warning_box(self, title: str, content: str):
        """경고 박스"""
        self.ln(5)

        # 빨간색 테두리
        self.set_draw_color(231, 76, 60)
        self.set_line_width(1)

        y_start = self.get_y()

        # 제목
        self.set_fill_color(231, 76, 60)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 11)
        self.cell(0, 8, f'  {title}', 0, 1, 'L', True)

        # 내용
        self.set_fill_color(254, 242, 242)
        self.set_text_color(0, 0, 0)
        self.add_text_with_font(content, size=9)

        # 박스 그리기
        y_end = self.get_y()
        self.rect(10, y_start, 190, y_end - y_start)

        self.ln(5)


class ExpertReportManager:
    """전문가급 리포트 생성 및 전송 관리"""

    def __init__(self):
        """초기화"""
        self.reports_dir = os.path.join(os.path.dirname(__file__), 'reports')
        self.temp_dir = os.path.join(os.path.dirname(__file__), 'temp')

        os.makedirs(self.reports_dir, exist_ok=True)
        os.makedirs(self.temp_dir, exist_ok=True)

    def save_chart_image(self, fig, filename: str) -> str:
        """차트를 이미지로 저장"""
        try:
            image_path = os.path.join(self.temp_dir, filename)
            fig.write_image(image_path, width=1000, height=500, scale=2)
            return image_path
        except Exception as e:
            print(f"[WARN] Chart image save failed: {e}")
            return None

    def extract_analysis_sections(self, analysis_text: str) -> Dict[str, str]:
        """분석 텍스트에서 섹션 추출"""
        sections = {
            'data_narrative': '',
            'disclosure': '',
            'bullish_bearish': '',
            'conclusion': '',
            'reliability': ''
        }

        # 섹션 패턴 매칭
        patterns = {
            'data_narrative': r'###\s*1\.\s*데이터-내러티브 괴리.*?(?=###|$)',
            'disclosure': r'###\s*2\.\s*공시 진위.*?(?=###|$)',
            'bullish_bearish': r'###\s*3\.\s*강세론.*?(?=###|$)',
            'conclusion': r'###\s*4\.\s*종합 판단.*?(?=###|$)',
            'reliability': r'###\s*5\.\s*신뢰도 점수.*?(?=###|$)',
        }

        for key, pattern in patterns.items():
            match = re.search(pattern, analysis_text, re.DOTALL | re.IGNORECASE)
            if match:
                sections[key] = match.group(0).strip()

        return sections

    def calculate_risk_score(self, analysis_text: str) -> int:
        """AI 위험 신호 점수 계산 (0-100, 높을수록 위험)"""
        risk_score = 50  # 기본값

        # 부정적 키워드
        negative_keywords = [
            '위험', '하락', '악재', '우려', '부정적', '감소',
            '약세', '하방', '주의', '경고', '데드크로스'
        ]

        # 긍정적 키워드
        positive_keywords = [
            '상승', '호재', '긍정적', '증가', '강세',
            '상방', '개선', '골든크로스', '회복'
        ]

        # 키워드 카운트
        for keyword in negative_keywords:
            risk_score += analysis_text.count(keyword) * 2

        for keyword in positive_keywords:
            risk_score -= analysis_text.count(keyword) * 2

        # 신뢰도 점수 추출
        reliability_match = re.search(r'점수:\s*(\d+)', analysis_text)
        if reliability_match:
            reliability = int(reliability_match.group(1))
            # 신뢰도가 낮으면 위험도 증가
            if reliability < 60:
                risk_score += (60 - reliability) // 2

        return max(0, min(100, risk_score))

    def generate_ai_self_criticism(self, analysis_text: str, stock_data: Dict) -> str:
        """AI 자기 비판 섹션 생성"""
        criticism = """
이 리포트는 AI가 생성한 것으로, 다음과 같은 근본적인 한계를 가지고 있습니다:

**1. 데이터 불완전성**
"""

        # 데이터 품질 평가
        if not stock_data or 'data' not in stock_data:
            criticism += "- 주가 데이터가 없거나 불충분합니다.\n"
        else:
            data_count = len(stock_data.get('data', []))
            if data_count < 7:
                criticism += f"- 주가 데이터가 {data_count}일분만 제공되어 장기 추세 파악이 불가능합니다.\n"

        criticism += """
**2. 시점 차이 문제**
- 이 리포트는 과거 데이터를 기반으로 작성되었습니다.
- 실시간 시장 상황과 큰 차이가 있을 수 있습니다.
- 뉴스와 공시는 수집 시점 기준이며, 최신 정보가 누락되었을 가능성이 있습니다.

**3. AI 할루시네이션 가능성**
- AI는 때때로 존재하지 않는 정보를 그럴듯하게 생성할 수 있습니다.
- 모든 수치와 분석은 반드시 원본 소스를 통해 재확인해야 합니다.
- 특히 '예측'이나 '전망'은 AI의 추론일 뿐 확정된 사실이 아닙니다.

**4. 맥락 부족**
- 거시경제 상황, 업종 전체 동향, 경쟁사 분석 등이 누락되었습니다.
- 단일 종목만 분석했기 때문에 상대적 비교가 불가능합니다.

**5. 감정과 편향**
- AI는 학습 데이터의 편향을 그대로 반영할 수 있습니다.
- 뉴스 헤드라인의 과장된 표현이 분석에 영향을 주었을 가능성이 있습니다.

**[WARN] 결론: 이 리포트는 참고 자료일 뿐입니다**

투자 결정은 반드시:
1. 복수의 정보원 교차 검증
2. 전문가 상담
3. 본인의 투자 원칙과 리스크 허용도 고려
4. 최신 공시 및 뉴스 직접 확인

위 과정을 거친 후에 내려야 합니다.
"""

        return criticism

    def create_expert_pdf(
        self,
        ticker: str,
        company_name: str,
        analysis_text: str,
        stock_data: Dict[str, Any],
        chart_fig=None,
        status_callback=None
    ) -> str:
        """
        전문가급 PDF 리포트 생성

        Args:
            ticker: 종목 티커
            company_name: 회사명
            analysis_text: AI 분석 텍스트
            stock_data: 주가 데이터
            chart_fig: Plotly 차트
            status_callback: 상태 업데이트 콜백

        Returns:
            PDF 파일 경로
        """
        if status_callback:
            status_callback("[DOC] PDF 문서 초기화 중...")

        # PDF 생성
        pdf = ProfessionalPDFReport()
        pdf.add_page()

        # 한글 폰트 설정
        korean_support = pdf.setup_korean_font()

        # === 페이지 1: 표지 ===
        if status_callback:
            status_callback("[EDIT] 표지 생성 중...")

        pdf.ln(20)
        pdf.set_font('Arial', 'B', 24)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(0, 15, company_name, 0, 1, 'C')

        pdf.set_font('Arial', '', 14)
        pdf.set_text_color(127, 140, 141)
        pdf.cell(0, 10, ticker, 0, 1, 'C')

        pdf.ln(10)

        # 기본 정보 박스
        pdf.add_key_value_box([
            ('Report Date', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
            ('Analysis Period', '7 Days'),
            ('AI Model', 'Claude Sonnet 4 (2025-05-14)'),
            ('Framework', 'Critical Reasoning + Self-Criticism'),
        ])

        # === 섹션 1: 데이터 기반 팩트 체크 ===
        pdf.add_page()

        if status_callback:
            status_callback("[DATA] 섹션 1: 데이터 팩트 체크 작성 중...")

        pdf.section_header('01', 'DATA-BASED FACT CHECK')

        if stock_data and 'data' in stock_data:
            data_list = stock_data['data']

            if data_list:
                first = data_list[0]
                last = data_list[-1]
                change = last['close'] - first['close']
                change_pct = (change / first['close']) * 100

                pdf.add_key_value_box([
                    ('Period', f"{first['date']} ~ {last['date']}"),
                    ('Opening Price', f"{first['close']:,.0f} KRW"),
                    ('Closing Price', f"{last['close']:,.0f} KRW"),
                    ('Change', f"{change:+,.0f} KRW ({change_pct:+.2f}%)"),
                    ('7-Day High', f"{max([d['high'] for d in data_list]):,.0f} KRW"),
                    ('7-Day Low', f"{min([d['low'] for d in data_list]):,.0f} KRW"),
                ])

        # 차트 삽입
        if chart_fig:
            if status_callback:
                status_callback("[CHART] 차트 이미지 생성 중...")

            chart_image = self.save_chart_image(chart_fig, f"chart_{ticker}.png")
            if chart_image and os.path.exists(chart_image):
                pdf.ln(5)
                pdf.image(chart_image, x=10, w=190)

        # === 섹션 2: AI 비판적 분석 ===
        pdf.add_page()

        if status_callback:
            status_callback("[AI] 섹션 2: AI 비판적 분석 작성 중...")

        pdf.section_header('02', 'AI CRITICAL ANALYSIS')

        sections = self.extract_analysis_sections(analysis_text)

        # 분석 내용 추가
        for section_text in [sections['data_narrative'], sections['disclosure'],
                              sections['bullish_bearish'], sections['conclusion']]:
            if section_text:
                lines = section_text.split('\n')
                for line in lines:
                    if line.strip():
                        if line.startswith('###'):
                            # 소제목
                            title = line.replace('###', '').strip()
                            pdf.ln(3)
                            pdf.set_font('Arial', 'B', 11)
                            pdf.set_text_color(52, 73, 94)
                            pdf.multi_cell(0, 6, title)
                            pdf.ln(2)
                        else:
                            # 본문
                            pdf.add_text_with_font(line.strip(), size=10)

        # === 섹션 3: 기술적 지표 요약 ===
        pdf.add_page()

        if status_callback:
            status_callback("[CHART] 섹션 3: 기술적 지표 요약 작성 중...")

        pdf.section_header('03', 'TECHNICAL INDICATORS SUMMARY')

        # 신뢰도 점수
        if sections['reliability']:
            pdf.add_text_with_font(sections['reliability'], size=10)

        # === 섹션 4: AI 자기 비판 (Self-Criticism) ===
        pdf.add_page()

        if status_callback:
            status_callback("[WARN] 섹션 4: AI 자기 비판 작성 중...")

        pdf.section_header('04', 'AI SELF-CRITICISM', color=(231, 76, 60))

        self_criticism = self.generate_ai_self_criticism(analysis_text, stock_data)

        pdf.add_warning_box(
            '[WARN] CRITICAL WARNING',
            self_criticism
        )

        # PDF 저장
        if status_callback:
            status_callback("[SAVE] PDF 파일 저장 중...")

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"EXPERT_REPORT_{company_name}_{timestamp}.pdf"
        filepath = os.path.join(self.reports_dir, filename)

        pdf.output(filepath)

        # 임시 파일 정리
        if chart_fig:
            chart_image = os.path.join(self.temp_dir, f"chart_{ticker}.png")
            if os.path.exists(chart_image):
                try:
                    os.remove(chart_image)
                except:
                    pass

        if status_callback:
            status_callback("[OK] PDF 생성 완료!")

        return filepath

    def send_intelligent_email(
        self,
        pdf_path: str,
        company_name: str,
        ticker: str,
        analysis_text: str,
        risk_score: int,
        status_callback=None
    ) -> bool:
        """
        지능형 HTML 이메일 전송

        Args:
            pdf_path: PDF 파일 경로
            company_name: 회사명
            ticker: 티커
            analysis_text: 분석 텍스트
            risk_score: AI 위험 신호 점수
            status_callback: 상태 업데이트 콜백

        Returns:
            성공 여부
        """
        if status_callback:
            status_callback("[EMAIL] 이메일 설정 확인 중...")

        # 환경변수 로드
        sender_email = os.getenv('SENDER_EMAIL')
        app_password = os.getenv('APP_PASSWORD')
        recipient_email = os.getenv('RECIPIENT_EMAIL')

        if not all([sender_email, app_password, recipient_email]):
            print("[ERROR] Email settings missing")
            return False

        try:
            if status_callback:
                status_callback("[EMAIL] 이메일 메시지 작성 중...")

            # 핵심 요약 추출 (3줄)
            summary_points = self._extract_key_points(analysis_text)

            # 위험도 등급
            if risk_score >= 70:
                risk_level = "[HIGH] HIGH RISK"
                risk_color = "#e74c3c"
            elif risk_score >= 40:
                risk_level = "[MODERATE] MODERATE RISK"
                risk_color = "#f39c12"
            else:
                risk_level = "[LOW] LOW RISK"
                risk_color = "#27ae60"

            # HTML 이메일 본문
            html_body = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                   color: white; padding: 30px; text-align: center; border-radius: 10px; }}
        .content {{ background: #f8f9fa; padding: 30px; margin-top: 20px; border-radius: 10px; }}
        .risk-badge {{ display: inline-block; padding: 10px 20px; border-radius: 20px;
                       background: {risk_color}; color: white; font-weight: bold; margin: 20px 0; }}
        .summary {{ background: white; padding: 20px; border-left: 4px solid #667eea;
                    margin: 20px 0; border-radius: 5px; }}
        .summary li {{ margin: 10px 0; }}
        .footer {{ text-align: center; color: #7f8c8d; margin-top: 30px; font-size: 12px; }}
        .warning {{ background: #fff3cd; border-left: 4px solid #f39c12;
                    padding: 15px; margin: 20px 0; border-radius: 5px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>[DATA] GLOBAL MACRO INTELLIGENCE</h1>
            <p>Professional Critical Analysis Report</p>
        </div>

        <div class="content">
            <h2>{company_name} ({ticker})</h2>
            <p><strong>Report Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

            <div style="text-align: center;">
                <div class="risk-badge">{risk_level}</div>
                <p><strong>AI Risk Score: {risk_score}/100</strong></p>
            </div>

            <div class="summary">
                <h3>[LIST] 핵심 요약 (Key Summary)</h3>
                <ul>
                    {''.join([f'<li>{point}</li>' for point in summary_points])}
                </ul>
            </div>

            <div class="warning">
                <strong>[WARN] 주의사항:</strong><br>
                이 리포트는 AI가 생성한 것으로, 투자 권유가 아닌 참고 자료입니다.
                실제 투자 결정 전 반드시 복수의 정보원을 통해 교차 검증하시기 바랍니다.
            </div>

            <p style="margin-top: 30px;">
                <strong>첨부 파일:</strong><br>
                [ATTACH] {os.path.basename(pdf_path)}
            </p>

            <p>
                상세한 분석 내용은 첨부된 PDF 리포트를 참조하시기 바랍니다.<br>
                PDF에는 다음이 포함되어 있습니다:
            </p>
            <ul>
                <li>데이터 기반 팩트 체크</li>
                <li>AI 비판적 분석</li>
                <li>기술적 지표 요약</li>
                <li>AI 자기 비판 (한계 분석)</li>
            </ul>
        </div>

        <div class="footer">
            <p>Generated by Claude Sonnet 4 | Global Macro Intelligence Hub</p>
            <p>이 메일은 자동으로 발송되었습니다.</p>
        </div>
    </div>
</body>
</html>
"""

            # 이메일 메시지 구성
            msg = MIMEMultipart('alternative')
            msg['From'] = sender_email
            msg['To'] = recipient_email
            msg['Subject'] = f"[{risk_level}] {company_name} 전문가 분석 리포트"

            # HTML 본문 첨부
            msg.attach(MIMEText(html_body, 'html', 'utf-8'))

            # PDF 첨부
            if status_callback:
                status_callback("[ATTACH] PDF 파일 첨부 중...")

            with open(pdf_path, 'rb') as f:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    'Content-Disposition',
                    f'attachment; filename= {os.path.basename(pdf_path)}'
                )
                msg.attach(part)

            # SMTP 전송
            if status_callback:
                status_callback("[EXPORT] 이메일 전송 중...")

            # 앱 비밀번호에서 공백 제거
            app_password_clean = app_password.replace(' ', '')

            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(sender_email, app_password_clean)
            server.sendmail(sender_email, recipient_email, msg.as_string())
            server.quit()

            if status_callback:
                status_callback("[OK] 이메일 전송 완료!")

            return True

        except Exception as e:
            print(f"[ERROR] 이메일 전송 실패: {str(e)}")
            if status_callback:
                status_callback(f"[ERROR] 전송 실패: {str(e)}")
            return False

    def _extract_key_points(self, analysis_text: str) -> List[str]:
        """분석 텍스트에서 핵심 포인트 3개 추출"""
        points = []

        # 강세론/약세론 추출
        bullish_match = re.search(r'\*\*강세론.*?\*\*.*?1\.\s*(.+?)(?:\n|$)', analysis_text, re.DOTALL)
        bearish_match = re.search(r'\*\*약세론.*?\*\*.*?1\.\s*(.+?)(?:\n|$)', analysis_text, re.DOTALL)

        if bullish_match:
            points.append(f"[CHART] 강세 요인: {bullish_match.group(1).strip()[:100]}")

        if bearish_match:
            points.append(f"[CHART] 약세 요인: {bearish_match.group(1).strip()[:100]}")

        # 신뢰도 점수
        reliability_match = re.search(r'점수:\s*(\d+)', analysis_text)
        if reliability_match:
            score = int(reliability_match.group(1))
            points.append(f"[TARGET] 신뢰도 점수: {score}/100")

        # 부족하면 기본 메시지
        while len(points) < 3:
            points.append("상세 내용은 PDF 리포트를 참조하세요.")

        return points[:3]

    def generate_and_send_expert_report(
        self,
        ticker: str,
        company_name: str,
        analysis_text: str,
        stock_data: Dict[str, Any],
        chart_fig=None,
        status_callback=None
    ) -> bool:
        """
        전문가급 PDF 생성 및 지능형 이메일 전송 (일괄 처리)

        Args:
            ticker: 종목 티커
            company_name: 회사명
            analysis_text: 분석 텍스트
            stock_data: 주가 데이터
            chart_fig: 차트
            status_callback: 상태 업데이트 콜백

        Returns:
            성공 여부
        """
        try:
            # 1. PDF 생성
            pdf_path = self.create_expert_pdf(
                ticker=ticker,
                company_name=company_name,
                analysis_text=analysis_text,
                stock_data=stock_data,
                chart_fig=chart_fig,
                status_callback=status_callback
            )

            if not pdf_path or not os.path.exists(pdf_path):
                return False

            # 2. 위험 점수 계산
            risk_score = self.calculate_risk_score(analysis_text)

            # 3. 이메일 전송
            success = self.send_intelligent_email(
                pdf_path=pdf_path,
                company_name=company_name,
                ticker=ticker,
                analysis_text=analysis_text,
                risk_score=risk_score,
                status_callback=status_callback
            )

            return success

        except Exception as e:
            print(f"[ERROR] 리포트 생성/전송 실패: {str(e)}")
            if status_callback:
                status_callback(f"[ERROR] 오류 발생: {str(e)}")
            return False


def main():
    """테스트"""
    manager = ExpertReportManager()

    test_data = {
        "ticker": "005930.KS",
        "company_name": "삼성전자",
        "analysis_text": "### 1. 데이터-내러티브 괴리 분석\n테스트\n### 3. 강세론 vs 약세론\n**강세론**\n1. 테스트",
        "stock_data": {
            "data": [
                {"date": "2026-02-01", "open": 75000, "high": 76000, "low": 74000, "close": 75500, "volume": 10000000},
            ]
        }
    }

    pdf_path = manager.create_expert_pdf(
        ticker=test_data["ticker"],
        company_name=test_data["company_name"],
        analysis_text=test_data["analysis_text"],
        stock_data=test_data["stock_data"]
    )

    print(f"\n[OK] 테스트 PDF: {pdf_path}")


if __name__ == "__main__":
    main()
